import {useState,useEffect} from 'react';
import {NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {Zap,LayoutDashboard,FolderKanban,Grid2X2,ClipboardCheck,Activity,Users,UserCog,Package,Wallet,ChartNoAxesCombined,Files,Settings,Search,ChevronRight,Sun,Moon,Menu,X,Globe,ArrowUpRight,HardHat,LogOut,OctagonAlert,ListChecks,Lock} from 'lucide-react';
import {useLanguage} from '../lib/i18n';
import {useWorkspace} from '../lib/store';
import {useAuth,canUsers} from '../lib/auth';
import {percent} from '../lib/api';
import {ProgressBar} from './Common';
import {UnitDrawer} from './UnitDrawer';
import {NotificationsBell} from './Notifications';
import {TabBar} from './TabBar';
const nav=[['overview','/',LayoutDashboard],['projects','/projects',FolderKanban],['units','/units',Grid2X2],['inspections','/inspections',ClipboardCheck],['defects','/defects',OctagonAlert],['tasks','/tasks',ListChecks],['testing','/testing',Activity],['workforce','/workforce',Users],['materials','/materials',Package],['expenses','/expenses',Wallet],['reports','/reports',ChartNoAxesCombined],['references','/references',Files]];
export const Layout=()=>{
 const {t,lang,setLang}=useLanguage();const {data,projects,pid,setPid,error,refresh}=useWorkspace();const {user,logout}=useAuth();const location=useLocation(),navigate=useNavigate();const [menu,setMenu]=useState(false),[search,setSearch]=useState(''),[dark,setDark]=useState(localStorage.getItem('voltcraft-dark')==='true');
 const roleNav=nav.filter(([key])=>{if(user?.role==='worker')return['overview','units','defects','tasks'].includes(key);if(key==='expenses'&&user?.role==='supervisor')return false;return true;});
 const fullNav=canUsers(user)?[...roleNav,['users','/users',UserCog]]:roleNav;
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('voltcraft-dark',String(dark));},[dark]);
 useEffect(()=>{setMenu(false);window.scrollTo(0,0);},[location.pathname]);
 const current=fullNav.find(n=>n[1]===location.pathname)?.[0]||'settings',pending=data?.inspections.filter(i=>i.status==='pending').length||0;
 return <div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><NavLink to="/" className="brand" data-testid="brand-link"><span className="brand-symbol"><Zap size={25} strokeWidth={2.4}/></span><div>voltcraft<span>SITE OPERATIONS</span></div><span className="brand-dot"/></NavLink><button className="mobile-close icon-button" data-testid="close-navigation" onClick={()=>setMenu(false)}><X/></button><div className="project-switch"><span className="project-icon"><FolderKanban size={19}/></span><div><span className="small-label">{t('activeProject')}</span><select data-testid="project-selector" value={pid} onChange={e=>{setPid(e.target.value);navigate('/');}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div><div className="nav-group-label">{t('workspace')}</div><nav>{fullNav.map(([key,path,Icon])=><div key={key}>{key==='workforce'&&<div className="nav-group-label resource-label">{t('resources')}</div>}<NavLink end={path==='/'} to={path} data-testid={`nav-${key}`} className={({isActive})=>`nav-link ${isActive?'active':''}`}><Icon size={18}/><span>{t(user?.role==='worker'&&key==='overview'?'home':key)}</span>{key==='inspections'&&pending>0&&<b className="nav-count">{pending}</b>}</NavLink></div>)}</nav><div className="sidebar-bottom"><div className="site-pulse"><div><span className="pulse-dot"/>{t('overallProgress')}<b>{percent(data?.units||[])}%</b></div><ProgressBar id="sidebar-progress" value={percent(data?.units||[])}/></div>{user?.role!=='worker'&&<NavLink to="/settings" className="nav-link" data-testid="nav-settings"><Settings size={18}/>{t('settings')}</NavLink>}<div className="workspace-person"><span><HardHat size={21}/></span><div>{user?.name}<small>{t(user?.role||'viewer')} · {data?.project.company||'VoltCraft Electrical'}</small></div>{user?.role==='worker'&&<button className="icon-button" data-testid="nav-change-password" title={t('changePassword')} onClick={()=>navigate('/settings/password')}><Lock size={17}/></button>}<button className="icon-button" data-testid="logout-button" title={t('signOut')} onClick={logout}><LogOut size={17}/></button></div></div></aside>{menu&&<button className="mobile-scrim" aria-label={t('closeMenu')} data-testid="navigation-scrim" onClick={()=>setMenu(false)}/>}
 <div className="workspace-main"><header className="topbar"><div className="breadcrumb"><button className="icon-button menu-toggle" data-testid="open-navigation" onClick={()=>setMenu(true)}><Menu size={21}/></button><span>{t('workspace')}</span><ChevronRight size={13}/><b data-testid="breadcrumb-current">{t(current)}</b></div><div className="header-controls"><form className="global-search" data-testid="global-search-form" onSubmit={e=>{e.preventDefault();navigate(`/units?q=${encodeURIComponent(search)}`);}}><Search size={16}/><input data-testid="global-search-input" aria-label={t('searchUnits')} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('searchUnits')}/><span>↵</span></form><div className="language-control"><Globe size={15}/><select data-testid="language-selector" aria-label={t('language')} value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="bn">বাংলা</option><option value="zh">中文</option></select></div><button className="icon-button theme-toggle" data-testid="theme-toggle" title={t(dark?'lightMode':'darkMode')} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><NotificationsBell/><span className="header-avatar" data-testid="workspace-avatar"><HardHat size={19}/></span></div></header><main className="main-content" key={pid}>{error?<div className="error-state" data-testid="workspace-error">{error}<button data-testid="retry-workspace" onClick={refresh}>{t('retry')}</button></div>:data?<Outlet/>:<div className="loading-state" data-testid="loading-state"><Zap className="loading-zap"/>{t('loading')}</div>}<footer className="page-footer"><span>voltcraft <i>/</i> {t('scope')}</span><span><i className="pulse-dot"/> Singapore, SGT</span></footer></main></div><UnitDrawer/><TabBar/></div>;
};