import {useState,useEffect} from 'react';
import {useNavigate} from 'react-router-dom';
import {Check,Lock,ArrowRight,ClipboardCheck,Plus,Activity,Save,RotateCcw,Camera} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
import {Button} from './ui/button';
import {useLanguage} from '../lib/i18n';
import {useWorkspace} from '../lib/store';
import {useAuth,canWrite} from '../lib/auth';
import {label,status,fmtDateTime} from '../lib/api';
import {StatusBadge,ProgressBar,FormModal,Action,Empty} from './Common';
import {InspectionRequest,InspectionDecision} from './InspectionForms';
import {PhotoUpload,PhotoGallery} from './Photos';
import {toast} from 'sonner';
export const UnitDrawer=()=>{
 const {t,lang}=useLanguage();const {data,selectedUnit,setSelectedUnit,mutate}=useWorkspace();const {user}=useAuth();const ro=!canWrite(user);const [tab,setTab]=useState('workflow'),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[note,setNote]=useState('');const navigate=useNavigate();const [photoPoint,setPhotoPoint]=useState(null),[photoTick,setPhotoTick]=useState(0);
 useEffect(()=>{setTab('workflow');setModal(null);setNote('');setPhotoPoint(null);},[selectedUnit]);
 const u=data?.units.find(x=>x.id===selectedUnit);if(!u)return null;
 const unitDefects=(data.defects||[]).filter(d=>d.unit_id===u.id);
 const inspection=data.inspections.find(i=>i.unit_id===u.id&&i.status==='pending');const tests=data.tests.filter(x=>x.unit_id===u.id).sort((a,b)=>a.created_at.localeCompare(b.created_at));const latest=Object.fromEntries(tests.map(x=>[x.point_id,x]));const allPass=u.points.length>0&&u.points.every(p=>latest[p.id]?.result==='pass');const passCount=u.points.filter(p=>latest[p.id]?.result==='pass').length;
 const advance=async()=>{setBusy(true);try{await mutate('post',`/units/${u.id}/advance`,{expected_stage:u.stage,note});setNote('');toast.success(t('saved'));}catch{}finally{setBusy(false);}};
 return <Sheet open={!!u} onOpenChange={v=>!v&&setSelectedUnit(null)}><SheetContent className="unit-drawer" data-testid="unit-drawer"><SheetHeader><div className="drawer-eyebrow">{t('block')} {u.block} <span>/</span> {t('level')} {u.level}</div><SheetTitle data-testid="unit-drawer-title">{t('unit')} {label(u)}</SheetTitle><SheetDescription data-testid="unit-drawer-subtitle">{u.unit_type} <span>·</span> {u.assigned_to||t('unassigned')}</SheetDescription></SheetHeader><div className="drawer-status"><StatusBadge id="drawer-unit-status" value={status(u)}/><span className="mono" data-testid="drawer-unit-progress">{u.stage} / 9 {t('completed')}</span></div><ProgressBar value={Math.round(u.stage/9*100)} id="drawer-progress"/><div className="drawer-tabs">{['workflow','defects','testPoints','details','history'].map(k=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)} data-testid={`drawer-tab-${k}`}>{t(k)}</button>)}</div>
 {tab==='workflow'&&<><div className="workflow-steps">{Array.from({length:9},(_,i)=><div key={i} className={`workflow-step ${i<u.stage?'done':i===u.stage?'current':'locked'}`} data-testid={`workflow-step-${i}`}><div className="step-symbol">{i<u.stage?<Check size={16}/>:i>u.stage?<Lock size={12}/>:String(i+1).padStart(2,'0')}</div><div><strong>{t(`stage${i}`)}</strong>{i===u.stage&&<small>{t('current')}</small>}</div>{i<u.stage&&<span>{t('completed')}</span>}</div>)}</div>{u.stage<9&&!ro&&<div className="drawer-action-box">{u.stage===5?<><div className="hold-note"><Lock size={15}/>{t('plasterLocked')}</div><Action id="drawer-rto-action" icon={ClipboardCheck} onClick={()=>setModal(inspection?'review':'request')}>{t(inspection?'reviewInspection':'requestRto')}</Action></>:<><label className="field-label">{t('note')}<textarea data-testid="stage-update-note" value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label>{u.stage===8&&!allPass&&<button className="text-link" data-testid="go-test-points" onClick={()=>setTab('testPoints')}>{t('recordTest')}<ArrowRight size={15}/></button>}<Action id="complete-stage" disabled={busy||(u.stage===8&&!allPass)} icon={Check} onClick={advance}>{t(u.stage===8?'completeUnit':'markComplete')}</Action>{u.stage===8&&<p className="complete-hint" data-testid="complete-progress-hint">{u.points.length===0?t('completeBlockedNoPoints'):t('testPointsProgress').replace('{passed}',passCount).replace('{total}',u.points.length)}</p>}</>}</div>}</>}
 {tab==='defects'&&<div className="unit-defects">{unitDefects.length?unitDefects.map(d=><button key={d.id} className="defect-row" data-testid={`unit-defect-${d.id}`} onClick={()=>{setSelectedUnit(null);navigate(`/defects?open=${d.id}`);}}><div><strong>{d.title}</strong><small>{t(d.severity)} · {t(d.category)} · {d.reported_by?.name}</small></div><StatusBadge value={d.status} id={`unit-defect-status-${d.id}`}/></button>):<Empty text={t('noDefects')}/>}</div>}
 {tab==='testPoints'&&<div className="points-panel"><div className="points-header"><h3>{u.points.length} {t('testPoints')}</h3>{!ro&&<Action id="drawer-add-point" secondary disabled={u.stage===9} onClick={()=>setModal('point')}>{t('addPoint')}</Action>}</div>{u.points.map(p=><div key={p.id}><div className="point-row" data-testid={`point-${p.id}`}><span className="point-icon"><Activity size={17}/></span><div><strong>{p.name}</strong><small>{t(p.kind)}{latest[p.id]&&` · ${latest[p.id].l_n} / ${latest[p.id].l_e} / ${latest[p.id].n_e} MΩ`}</small></div>{latest[p.id]&&<StatusBadge value={latest[p.id].result} id={`point-result-${p.id}`}/>} {latest[p.id]&&<button className="icon-button" title={t('photos')} data-testid={`point-photos-${p.id}`} onClick={()=>setPhotoPoint(photoPoint===p.id?null:p.id)}><Camera size={16}/></button>}<button className="icon-button" disabled={u.stage!==8||ro} title={t('recordTest')} onClick={()=>setModal({test:p})} data-testid={`record-test-${p.id}`}><Plus size={18}/></button></div>{photoPoint===p.id&&latest[p.id]&&<div className="point-photos" data-testid={`point-photos-panel-${p.id}`}><PhotoGallery entityType="test" entityId={latest[p.id].id} refreshKey={photoTick} canDelete={!ro} id={`test-photos-${p.id}`}/>{!ro&&<PhotoUpload entityType="test" entityId={latest[p.id].id} onUploaded={()=>setPhotoTick(k=>k+1)} id={`test-photo-upload-${p.id}`}/>}</div>}</div>)}<p className="test-disclaimer" data-testid="test-disclaimer">{t('testDisclaimer')}</p>{u.stage===8&&!ro&&<><Action id="complete-tested-unit" icon={Check} disabled={!allPass||busy} onClick={advance}>{t('completeUnit')}</Action><p className="complete-hint" data-testid="complete-progress-hint">{u.points.length===0?t('completeBlockedNoPoints'):t('testPointsProgress').replace('{passed}',passCount).replace('{total}',u.points.length)}</p></>}</div>}
 {tab==='details'&&<div className="unit-details"><dl>{[['block',u.block],['level',u.level],['unit',label(u)],['unitType',u.unit_type],['team',u.assigned_to||t('unassigned')],['note',u.note||'—']].map(([k,v])=><div key={k}><dt>{t(k)}</dt><dd data-testid={`unit-detail-${k}`}>{v}</dd></div>)}</dl>{!ro&&<Action id="edit-unit-details" icon={Save} onClick={()=>setModal('edit')}>{t('edit')}</Action>}{u.sample&&!ro&&<button className="reset-sample" data-testid="reset-sample-unit" onClick={async()=>{if(window.confirm(t('resetConfirm'))){try{await mutate('post',`/units/${u.id}/reset-sample`,{});toast.success(t('saved'));}catch{}}}}><RotateCcw size={15}/>{t('resetSample')}</button>}</div>}
 {tab==='history'&&<div className="unit-history">{u.history.length?u.history.slice().reverse().map((h,i)=><div key={i} data-testid={`unit-history-${i}`}><span className="history-dot"/><strong>{t(`stage${h.stage}`)}</strong><p>{h.note||t('completed')}</p>{h.inspector&&<small>{h.inspector} · {t(h.result)}</small>}<time>{fmtDateTime(h.at,lang)}</time></div>):<Empty text={t('noHistory')}/>}</div>}
 {modal==='request'&&<InspectionRequest unit={u} onClose={()=>setModal(null)}/>} {modal==='review'&&inspection&&<InspectionDecision inspection={inspection} onClose={()=>setModal(null)}/>}
 {modal==='edit'&&<FormModal open onClose={()=>setModal(null)} title={t('details')} initial={{level:u.level,number:u.number,unit_type:u.unit_type,assigned_to:u.assigned_to,note:u.note}} fields={[{name:'level',label:t('level'),type:'number',min:1,max:data.blocks.find(b=>b.id===u.block_id)?.levels},{name:'number',label:t('unit')},{name:'unit_type',label:t('unitType'),options:['2-room Flexi','3-room','4-room','5-room']},{name:'assigned_to',label:t('team'),required:false},{name:'note',label:t('note'),type:'textarea',wide:true,required:false}]} onSubmit={v=>mutate('patch',`/units/${u.id}`,v)}/>}
 {modal==='point'&&<FormModal open onClose={()=>setModal(null)} title={t('addPoint')} initial={{name:'',kind:'power'}} fields={[{name:'name',label:t('point')},{name:'kind',label:t('kind'),options:['power','light','socket','switch','aircon','heater','fan','data'].map(k=>({value:k,label:t(k)}))}]} onSubmit={v=>mutate('post',`/units/${u.id}/points`,v)}/>}
 {modal?.test&&<FormModal open onClose={()=>setModal(null)} title={`${t('recordTest')} · ${modal.test.name}`} initial={{point_id:modal.test.id,voltage:'',l_n:'',l_e:'',n_e:'',result:'pass',tested_by:'',note:''}} fields={[{name:'voltage',label:t('voltage'),type:'number',min:1,max:5000},{name:'tested_by',label:t('testedBy')},{name:'l_n',label:'L–N (MΩ)',type:'number',min:0},{name:'l_e',label:'L–E (MΩ)',type:'number',min:0},{name:'n_e',label:'N–E (MΩ)',type:'number',min:0},{name:'result',label:t('result'),options:[{value:'pass',label:t('pass')},{value:'fail',label:t('fail')}]},{name:'note',label:t('note'),required:false,type:'textarea',wide:true}]} onSubmit={v=>mutate('post',`/units/${u.id}/tests`,v)}/>}
 </SheetContent></Sheet>;
};