import {useNavigate} from 'react-router-dom';
import {Building2,TrendingUp,ClipboardCheck,Users,ArrowUpRight,MapPin,CalendarDays,Check,Activity,OctagonAlert,ListChecks,Package,Clock3} from 'lucide-react';
import {useLanguage} from '../lib/i18n';
import {useWorkspace} from '../lib/store';
import {percent,today,stageName,stagesOf} from '../lib/api';
import {assigneeNames} from '../lib/planTasks';
import {PageTitle,Metric,SectionTitle,TextLink,ProgressBar,ExportButton,Action,Empty} from '../components/Common';
import '../fixes-b.css';
// Stage chart colors; cycles (modulo) when a project configures more than 9 stages.
const STAGE_PALETTE=['#3369ed','#4d80f1','#6391f5','#78a2f6','#9abaf8','#e4b35b','#8cb7a1','#54a485','#228d68'];
export default function Overview(){
 const {t,lang}=useLanguage();const {data,setSelectedUnit}=useWorkspace();const navigate=useNavigate();const {units,blocks,inspections,attendance,materials,activity,project,defects,tasks}=data;const stages=stagesOf(data),sc=stages.length,p=percent(units,sc),pending=inspections.filter(i=>i.status==='pending'),low=materials.filter(m=>m.stock<m.minimum),present=attendance.filter(a=>a.date===today()&&a.status==='present').length;
 const openDefects=(defects||[]).filter(d=>!['verified','cancelled'].includes(d.status));
 const critical=openDefects.filter(d=>d.severity==='critical');
 const overdue=(tasks||[]).filter(x=>x.due_date&&x.due_date<today()&&!['done','cancelled'].includes(x.status));
 const date=new Intl.DateTimeFormat(lang==='bn'?'bn-BD':lang==='zh'?'zh-CN':'en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Singapore'}).format(new Date());
 const attentionTotal=pending.length+low.length+critical.length+overdue.length;
 return <div className="page-enter"><PageTitle title={t('siteOverview')} subtitle={t('overviewSub')}><span className="date-label"><CalendarDays size={15}/>{date}</span><ExportButton/><Action id="overview-update" icon={ArrowUpRight} onClick={()=>navigate('/units')}>{t('updateProgress')}</Action></PageTitle>
 <section className="banner-strip" data-testid="project-banner"><div className="banner-strip-main"><span className="mini-tag">{t('hdbResidential')}</span><h2 data-testid="project-name">{project.name}<span>/</span>{t('scope')}</h2><div className="banner-strip-meta"><MapPin size={13}/>{project.location}<span className="banner-divider"/>{blocks.length} {t('block')} · {units.length} {t('unitCount')}</div></div><div className="banner-strip-target"><span>{t('target')}</span><strong data-testid="project-target">{new Date(`${project.target_date}T12:00:00`).toLocaleDateString(lang==='zh'?'zh-CN':'en-GB',{day:'numeric',month:'short',year:'numeric'})}</strong><button data-testid="banner-project-link" onClick={()=>navigate('/projects')}>{t('goProject')}<ArrowUpRight size={16}/></button></div></section>
 <div className="overview-meta" data-testid="sample-workspace-note">{project.sample?<><span className="sample-dot"/>{t('sample')}<span className="meta-separator">·</span><span>{t('sampleNote')}</span></>:<span>{t('scopeSub')}</span>}</div>
 <div className="metrics-grid"><Metric id="metric-total-units" title={t('totalUnits')} value={units.length} sub={`${blocks.length} ${t('block')} · ${t('acrossBlocks')}`} icon={Building2} tone="blue"/><Metric id="metric-overall-progress" title={t('overallProgress')} value={<>{p}<small>%</small></>} sub={t('stagesComplete')} icon={TrendingUp} tone="green"/><Metric id="metric-pending-rto" title={t('pendingRto')} value={pending.length} sub={t('awaitingInspection')} icon={ClipboardCheck} tone="amber"/><Metric id="metric-workers" title={t('onSite')} value={present} sub={t('attendanceToday')} icon={Users} tone="violet"/><Metric id="metric-open-defects" title={t('openDefects')} value={openDefects.length} sub={`${critical.length} ${t('critical')}`} icon={OctagonAlert} tone="red"/></div>
 <section className="attention-section attention-top"><SectionTitle title={t('attention')}><span className="count-pill">{attentionTotal}</span></SectionTitle><div className="attention-list">{critical.slice(0,2).map(d=><button key={d.id} data-testid={`attention-${d.id}`} className="attention-item" onClick={()=>navigate(`/defects?open=${d.id}`)}><span className="attention-icon red"><OctagonAlert size={18}/></span><div><strong>{d.title}</strong><small>{t('criticalDefects')}{d.block&&<><i>·</i> {t('block')} {d.block}</>}</small></div><Chevron/></button>)}{pending.slice(0,3).map(i=><button key={i.id} data-testid={`attention-${i.id}`} className="attention-item" onClick={()=>setSelectedUnit(i.unit_id)}><span className="attention-icon amber"><ClipboardCheck size={18}/></span><div><strong>{t('block')} {i.block} <span>{i.unit_label}</span></strong><small>{t('pendingRto')} <i>·</i> {i.inspector}</small></div><Chevron/></button>)}{overdue.slice(0,2).map(x=><button key={x.id} data-testid={`attention-${x.id}`} className="attention-item" onClick={()=>navigate('/tasks')}><span className="attention-icon red"><ListChecks size={18}/></span><div><strong>{x.title}</strong><small>{t('overdueTasks')} <i>·</i> {x.due_date} <i>·</i> {assigneeNames(x,t)}</small></div><Chevron/></button>)}{low.slice(0,2).map(m=><button key={m.id} data-testid={`attention-${m.id}`} className="attention-item" onClick={()=>navigate('/materials')}><span className="attention-icon red"><Package size={18}/></span><div><strong>{m.name}</strong><small>{t('lowStock')} <i>·</i> {m.stock} {m.unit}</small></div><Chevron/></button>)}{!attentionTotal&&<p className="empty">{t('allGood')}</p>}</div><div className="attention-links">{critical.length>0&&<TextLink id="view-all-defects" onClick={()=>navigate('/defects')}>{t('defects')} · {t('viewAll')}</TextLink>}{overdue.length>0&&<TextLink id="view-all-tasks" onClick={()=>navigate('/tasks')}>{t('tasks')} · {t('viewAll')}</TextLink>}{pending.length>0&&<TextLink id="view-all-inspections" onClick={()=>navigate('/inspections')}>{t('inspections')} · {t('viewAll')}</TextLink>}{low.length>0&&<TextLink id="view-all-materials" onClick={()=>navigate('/materials')}>{t('materials')} · {t('viewAll')}</TextLink>}</div></section>
 {!blocks.length&&<div data-testid="no-blocks-empty"><Empty text={t('noBlocksYet')}/><TextLink id="overview-no-blocks-link" onClick={()=>navigate('/projects')}>{t('addBlock')}</TextLink></div>}
 <section className="block-section"><SectionTitle title={t('blockProgress')}><TextLink id="view-all-blocks" onClick={()=>navigate('/units')}>{t('viewTracker')}</TextLink></SectionTitle><div className="block-grid">{blocks.map(b=>{const bu=units.filter(u=>u.block_id===b.id),bp=percent(bu,sc),r=bu.filter(u=>u.rto==='pending').length;return <button key={b.id} className="block-card" data-testid={`block-card-${b.name}`} onClick={()=>navigate(`/units?block=${b.id}`)}><div className="block-card-top"><span className="block-building"><Building2 size={18}/></span><ArrowUpRight size={15}/></div><div className="block-name">{t('block')} {b.name}<span data-testid={`block-percent-${b.name}`}>{bp}<small>%</small></span></div><p>{b.levels} {t('levels')} <i>·</i> {bu.length} {t('unitCount')}</p><ProgressBar id={`block-progress-${b.name}`} value={bp}/><div className="block-card-footer">{r>0?<><i className="amber-dot"/>{r} {t('pendingRto')}</>:<><Check size={12}/>{t('allGood')}</>}</div></button>;})}</div></section>
 <div className="overview-lower"><section className="stages-section"><SectionTitle title={t('stageDistribution')}><span className="subtle-label">{units.length} {t('unitCount')}</span></SectionTitle><div className="stage-chart">{stages.map((s,i)=>{const count=units.filter(u=>u.stage>i).length;return <div className="stage-chart-row" key={s.id||i} data-testid={`stage-distribution-${i}`}><div className="stage-chart-label"><span>{String(i+1).padStart(2,'0')}</span>{stageName(s,t)}</div><div className="stage-chart-track"><span style={{width:`${units.length?count/units.length*100:0}%`,background:STAGE_PALETTE[i%STAGE_PALETTE.length]}}/></div><b>{count}</b></div>;})}</div><div className="chart-legend"><i/>{t('completed')}<span>{t('stagesComplete')}</span></div></section></div>
 <section className="activity-section"><SectionTitle title={t('recentActivity')}><Activity size={17}/></SectionTitle><div className="activity-grid">{activity.slice(0,4).map(a=><div className="activity-item" key={a.id} data-testid={`activity-${a.id}`}><span className={`activity-marker ${a.kind}`}/><div><p>{a.message}</p><small><Clock3 size={11}/>{new Date(a.created_at).toLocaleTimeString(lang==='zh'?'zh-CN':'en-SG',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Singapore'})} {t('sgt')}</small></div></div>)}</div></section></div>;
}
const Chevron=()=> <ArrowUpRight size={15} className="muted"/>;
