import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {MapPin,ArrowUpRight,Building2,CalendarDays,Layers3,FolderKanban} from 'lucide-react';
import {useWorkspace} from '../lib/store';
import {useLanguage} from '../lib/i18n';
import {useAuth,canProjects} from '../lib/auth';
import {today,percent} from '../lib/api';
import {PageTitle,Action,FormModal,Empty,SectionTitle,ProgressBar} from '../components/Common';
import {BlockModal} from '../components/BlockModal';
import {toast} from 'sonner';
export default function Projects(){const {t}=useLanguage();const {data,pid,setPid,projects,loadProjects,mutate}=useWorkspace();const {user}=useAuth();const proj=canProjects(user);const [modal,setModal]=useState(null);const [rename,setRename]=useState(null);const navigate=useNavigate();const projectFields=[{name:'name',label:t('projectName'),wide:true},{name:'location',label:t('location'),wide:true},{name:'company',label:t('company'),wide:true},{name:'budget',label:`${t('budget')} (SGD)`,type:'number',min:0},{name:'target_date',label:t('targetDate'),type:'date'}];
const delBlock=async(b,n)=>{if(n>0){toast.error(t('blockDeleteBlocked').replace('{n}',n));return;}if(!window.confirm(t('deleteBlockConfirm').replace('{name}',b.name)))return;await mutate('delete',`/projects/${pid}/blocks/${b.id}`);};
return <div className="page-enter"><PageTitle title={t('projects')} subtitle={t('projectSub')}>{proj&&<Action id="new-project" onClick={()=>setModal('project')}>{t('newProject')}</Action>}</PageTitle>{!projects.length&&<Empty text={t('noProjectsYet')}/>}
<div className="projects-grid">{projects.map((p,i)=><article key={p.id} className={`project-card ${pid===p.id?'selected':''}`} data-testid={`project-card-${p.id}`}><div className="project-card-image"><img src="/images/hdb-panorama.jpg" alt="Singapore residential buildings"/><span className="project-card-tag">HDB · ELECTRICAL</span>{p.sample&&<span className="project-sample">{t('sample')}</span>}</div><div className="project-card-content"><div className="project-card-heading"><h2>{p.name}</h2></div><p><MapPin size={13}/>{p.location}</p><div className="project-card-date"><CalendarDays size={13}/>{t('targetDate')}<span>{p.target_date}</span></div><button className="project-open-button" data-testid={`open-project-${p.id}`} onClick={()=>{setPid(p.id);navigate('/');}}>{t('goProject')}<ArrowUpRight size={16}/></button></div></article>)}</div><section className="project-blocks-section"><SectionTitle title={`${data.project.name} · ${t('blockProgress')}`}>{proj&&<Action id="add-block" secondary onClick={()=>setModal('block')}>{t('addBlock')}</Action>}</SectionTitle><div className="table-scroll"><table data-testid="project-blocks-table"><thead><tr>{['block','levels','totalUnits','progress','actions'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.blocks.map(b=>{const bu=data.units.filter(u=>u.block_id===b.id);return <tr key={b.id} data-testid={`project-block-${b.id}`}><td><div className="material-name"><Building2 size={17}/><strong>{t('block')} {b.name}</strong></div></td><td>{b.levels}</td><td>{bu.length}</td><td><div className="inline-progress"><ProgressBar value={percent(bu)} id={`project-block-progress-${b.id}`}/><span>{percent(bu)}%</span></div></td><td><div className="row-actions"><button data-testid={`project-block-open-${b.id}`} className="text-link" onClick={()=>navigate(`/units?block=${b.id}`)}>{t('view')}<ArrowUpRight size={15}/></button>{proj&&<button data-testid={`project-block-rename-${b.id}`} className="text-link" onClick={()=>setRename(b)}>{t('renameBlock')}</button>}{proj&&<button data-testid={`project-block-delete-${b.id}`} className="text-link" onClick={()=>delBlock(b,bu.length)}>{t('delete')}</button>}</div></td></tr>;})}</tbody></table></div>{!data.blocks.length&&<Empty text={t('noBlocksYet')}/>}</section>{modal==='project'&&<FormModal open title={t('newProject')} onClose={()=>setModal(null)} fields={projectFields} initial={{name:'',location:'Singapore',company:data.project.company,budget:0,target_date:today()}} onSubmit={async v=>{const p=await mutate('post','/projects',v);await loadProjects();setPid(p.id);navigate('/');}}/>}{rename&&<FormModal open title={t('renameBlock')} onClose={()=>setRename(null)} fields={[{name:'name',label:t('blockName'),wide:true}]} initial={{name:rename.name}} onSubmit={v=>mutate('patch',`/projects/${pid}/blocks/${rename.id}`,{name:v.name})}/>}{modal==='block'&&<BlockModal open onClose={()=>setModal(null)} onSubmit={v=>mutate('post',`/projects/${pid}/blocks`,v)}/>}</div>;}
