import React,{createContext,useContext,useState} from 'react';
const words = {
resetSample:['Reset sample progress','নমুনা অগ্রগতি মুছুন','重置示例进度'],resetConfirm:['Reset this sample unit to not started? Sample inspections and test records will be removed.','এই নমুনা ইউনিট শুরু হয়নি অবস্থায় ফেরাবেন? নমুনা পরিদর্শন ও টেস্ট মুছে যাবে।','将此示例单元重置为未开始？示例验收和测试记录将被删除。'],
overview:['Overview','সারসংক্ষেপ','总览'],projects:['Projects','প্রকল্প','项目'],units:['Unit tracker','ইউনিট ট্র্যাকার','单元追踪'],inspections:['RTO inspections','RTO পরিদর্শন','RTO 验收'],testing:['Insulation tests','ইনসুলেশন টেস্ট','绝缘测试'],workforce:['Workforce','শ্রমিক','施工人员'],materials:['Materials','মালামাল','材料'],expenses:['Expenses','খরচ','费用'],reports:['Reports','রিপোর্ট','报表'],references:['Site references','সাইটের নথি','现场图纸'],settings:['Project settings','প্রকল্প সেটিংস','项目设置'],
workspace:['WORKSPACE','কর্মক্ষেত্র','工作空间'],resources:['RESOURCES','রিসোর্স','资源'],siteOverview:['Site overview','সাইটের সারসংক্ষেপ','现场总览'],overviewSub:['Every block. Every point. One clear picture.','সব ব্লক, সব পয়েন্ট—এক নজরে।','每栋楼、每个点位，一目了然。'],activeProject:['ACTIVE PROJECT','চলমান প্রকল্প','进行中的项目'],active:['Active','চলমান','进行中'],sample:['Sample workspace','নমুনা কর্মক্ষেত্র','示例工作区'],sampleNote:['Block totals from your site reference. Unit layouts and site records are editable examples.','ছবির ব্লকের মোট সংখ্যা ব্যবহৃত। ইউনিট বিন্যাস ও কাজের তথ্য সম্পাদনাযোগ্য নমুনা।','楼栋总数来自现场图纸。单元布局与施工记录为可编辑示例。'],
ref0:['Site plan · Block schedule','সাইট প্ল্যান · ব্লকের তালিকা','总平面图 · 楼栋明细'],ref1:['Site layout · Block 36B','সাইটের বিন্যাস · ব্লক 36B','现场布局 · 36B 栋'],ref2:['Block 36A · Corridor circuits','ব্লক 36A · করিডর সার্কিট','36A 栋 · 走廊回路'],ref3:['Block 35C · Floor stacks','ব্লক 35C · তলার চার্ট','35C 栋 · 楼层矩阵'],ref4:['Block 35A · Floor stacks','ব্লক 35A · তলার চার্ট','35A 栋 · 楼层矩阵'],
totalUnits:['Total units','মোট ইউনিট','总单元数'],overallProgress:['Overall progress','সার্বিক অগ্রগতি','整体进度'],pendingRto:['Pending RTO','অপেক্ষমাণ RTO','待验收'],onSite:['Workers on site','সাইটে শ্রমিক','在场人员'],acrossBlocks:['across all blocks','সব ব্লক মিলিয়ে','所有楼栋'],stagesComplete:['of work stages complete','কাজের ধাপ সম্পন্ন','工序已完成'],awaitingInspection:['awaiting inspection','পরিদর্শনের অপেক্ষায়','等待验收'],attendanceToday:['attendance today','আজকের হাজিরা','今日出勤'],
blockProgress:['Block progress','ব্লকের অগ্রগতি','楼栋进度'],viewAll:['View all','সব দেখুন','查看全部'],viewTracker:['Open unit tracker','ইউনিট ট্র্যাকার খুলুন','打开单元追踪'],levels:['levels','তলা','层'],unitCount:['units','ইউনিট','单元'],completed:['Completed','সম্পন্ন','已完成'],inProgress:['In progress','চলমান','进行中'],pending:['Pending RTO','RTO অপেক্ষমাণ','待验收'],rework:['Rework','সংশোধন','需返工'],notStarted:['Not started','শুরু হয়নি','未开始'],stageDistribution:['Work stage distribution','কাজের ধাপ অনুযায়ী অগ্রগতি','工序分布'],attention:['Needs attention','মনোযোগ প্রয়োজন','需要关注'],recentActivity:['Recent activity','সাম্প্রতিক কার্যক্রম','最近动态'],lowStock:['Low stock','স্টক কম','库存不足'],allGood:['All clear','সব ঠিক আছে','暂无待办'],
export:['Export CSV','CSV ডাউনলোড','导出 CSV'],newProject:['New project','নতুন প্রকল্প','新建项目'],addBlock:['Add block','ব্লক যোগ','添加楼栋'],addUnit:['Add unit','ইউনিট যোগ','添加单元'],updateProgress:['Update progress','অগ্রগতি আপডেট','更新进度'],allBlocks:['All blocks','সব ব্লক','所有楼栋'],allStages:['All stages','সব ধাপ','所有工序'],allStatuses:['All statuses','সব অবস্থা','全部状态'],allLevels:['All levels','সব তলা','所有楼层'],searchUnits:['Search unit or team…','ইউনিট বা টিম খুঁজুন…','搜索单元或团队…'],search:['Search…','খুঁজুন…','搜索…'],matrix:['Floor matrix','তলার চার্ট','楼层矩阵'],list:['List view','তালিকা','列表'],block:['Block','ব্লক','楼栋'],level:['Level','তলা','楼层'],unit:['Unit','ইউনিট','单元'],unitType:['Unit type','ইউনিটের ধরন','户型'],currentStage:['Current stage','বর্তমান ধাপ','当前工序'],progress:['Progress','অগ্রগতি','进度'],team:['Assigned team','নির্ধারিত টিম','负责团队'],status:['Status','অবস্থা','状态'],actions:['Actions','করণীয়','操作'],noRecords:['No records found','কোনো তথ্য পাওয়া যায়নি','暂无记录'],
stage0:['Slab PVC laying','স্ল্যাব PVC বসানো','楼板 PVC 铺设'],stage1:['Casting complete','কাস্টিং সম্পন্ন','浇筑完成'],stage2:['Point hacking','পয়েন্ট হ্যাকিং','点位开凿'],stage3:['Wire pulling','তার টানা','穿线'],stage4:['GI/PVC & gang boxes','GI/PVC ও গ্যাং বক্স','GI/PVC 与底盒'],stage5:['RTO approval','RTO অনুমোদন','RTO 验收批准'],stage6:['Cement plastering','সিমেন্ট প্লাস্টার','水泥抹灰'],stage7:['Accessories fitting','সুইচ ও সকেট ফিটিং','开关插座安装'],stage8:['Insulation testing','ইনসুলেশন টেস্ট','绝缘测试'],
workflow:['Installation workflow','কাজের ধাপ','安装工序'],details:['Details','বিস্তারিত','详情'],testPoints:['Test points','টেস্ট পয়েন্ট','测试点位'],history:['History','ইতিহাস','历史'],markComplete:['Complete current stage','বর্তমান ধাপ সম্পন্ন করুন','完成当前工序'],requestRto:['Request RTO inspection','RTO পরিদর্শন অনুরোধ','申请 RTO 验收'],reviewInspection:['Review inspection','পরিদর্শন পর্যালোচনা','审核验收'],plasterLocked:['Plastering locked until RTO approval','RTO অনুমোদনের আগে প্লাস্টারিং বন্ধ','RTO 批准前不可抹灰'],completeUnit:['Complete unit','ইউনিট সম্পন্ন করুন','完成单元'],addPoint:['Add point','পয়েন্ট যোগ','添加点位'],recordTest:['Record test','টেস্ট সংরক্ষণ','记录测试'],note:['Notes','মন্তব্য','备注'],save:['Save changes','সংরক্ষণ','保存更改'],cancel:['Cancel','বাতিল','取消'],create:['Create','তৈরি করুন','创建'],saved:['Saved successfully','সফলভাবে সংরক্ষিত','保存成功'],delete:['Delete','মুছুন','删除'],edit:['Edit','সম্পাদনা','编辑'],confirmDelete:['Delete this record?','এই তথ্য মুছে ফেলবেন?','删除此记录？'],
inspector:['Inspector name','পরিদর্শকের নাম','验收员姓名'],date:['Date','তারিখ','日期'],approve:['Approve','অনুমোদন','批准'],requestRework:['Require rework','সংশোধন প্রয়োজন','要求返工'],approved:['Approved','অনুমোদিত','已批准'],inspectionNote:['Inspection findings','পরিদর্শনের বিবরণ','验收结果说明'],schedule:['Schedule inspection','পরিদর্শনের তারিখ দিন','安排验收'],inspectionSub:['Concealed works, approvals and rectification.','গোপন পাইপের কাজ, অনুমোদন ও সংশোধন।','隐蔽工程、验收与整改。'],testingSub:['Point-by-point readings and recorded test outcomes.','প্রতিটি পয়েন্টের রিডিং ও পরীক্ষার ফল।','逐点记录读数与测试结果。'],point:['Point','পয়েন্ট','点位'],kind:['Type','ধরন','类型'],voltage:['Test voltage (V DC)','টেস্ট ভোল্টেজ (V DC)','测试电压 (V DC)'],testedBy:['Tested by','পরীক্ষাকারী','测试人员'],result:['Result','ফলাফল','结果'],pass:['Pass','পাস','通过'],fail:['Fail','ফেল','未通过'],testDisclaimer:['Results are recorded by the tester; this record is not an electrical safety certificate.','পরীক্ষাকারীর দেওয়া ফল সংরক্ষিত হয়; এটি বৈদ্যুতিক নিরাপত্তার সনদ নয়।','结果由测试人员判定；本记录并非电气安全证书。'],
workersSub:['Your people, assignments and daily attendance.','শ্রমিক, দায়িত্ব ও প্রতিদিনের হাজিরা।','人员、分工与每日出勤。'],addWorker:['Add worker','শ্রমিক যোগ','添加人员'],name:['Name','নাম','名称'],trade:['Trade','কাজের ধরন','工种'],dailyRate:['Daily rate (SGD)','দৈনিক মজুরি (SGD)','日薪 (SGD)'],phone:['Phone','ফোন','电话'],attendance:['Attendance','হাজিরা','出勤'],present:['Present','উপস্থিত','出勤'],absent:['Absent','অনুপস্থিত','缺勤'],leave:['On leave','ছুটিতে','休假'],unmarked:['Not marked','চিহ্নিত হয়নি','未记录'],hours:['Hours','ঘণ্টা','工时'],estimatedLabour:['Estimated daily labour','আনুমানিক দৈনিক মজুরি','预计每日人工费'],totalWorkers:['Total workforce','মোট শ্রমিক','人员总数'],archive:['Archive worker','শ্রমিক আর্কাইভ','归档人员'],
materialsSub:['Keep the right materials ready for the next stage.','পরবর্তী ধাপের জন্য মালামালের প্রস্তুতি।','为下一工序备齐材料。'],addMaterial:['Add material','মালামাল যোগ','添加材料'],stock:['In stock','মজুত','库存'],minimum:['Minimum stock','ন্যূনতম মজুত','最低库存'],unitCost:['Unit cost (SGD)','একক মূল্য (SGD)','单价 (SGD)'],stockValue:['Inventory value','মজুতের মূল্য','库存价值'],receive:['Receive stock','স্টক গ্রহণ','入库'],issue:['Issue stock','স্টক প্রদান','出库'],quantity:['Quantity','পরিমাণ','数量'],movement:['Stock movement','স্টক লেনদেন','库存变动'],movements:['Recent stock movements','সাম্প্রতিক স্টক লেনদেন','近期库存变动'],healthy:['In stock','পর্যাপ্ত মজুত','库存充足'],material:['Material','মালামাল','材料'],measure:['Unit of measure','পরিমাপের একক','计量单位'],
expensesSub:['Every dollar accounted for, in Singapore dollars.','প্রতিটি খরচের হিসাব, Singapore dollars-এ।','以新加坡元清晰记录每笔支出。'],addExpense:['Add expense','খরচ যোগ','添加费用'],totalSpent:['Total expenses','মোট খরচ','总支出'],budget:['Project budget','প্রকল্পের বাজেট','项目预算'],remaining:['Budget remaining','অবশিষ্ট বাজেট','剩余预算'],description:['Description','বিবরণ','说明'],category:['Category','বিভাগ','类别'],amount:['Amount (SGD)','পরিমাণ (SGD)','金额 (SGD)'],reference:['Reference','রেফারেন্স','凭证编号'],labour:['Labour','শ্রমিক মজুরি','人工'],equipment:['Equipment','যন্ত্রপাতি','设备'],transport:['Transport','পরিবহন','运输'],other:['Other','অন্যান্য','其他'],allCategories:['All categories','সব বিভাগ','全部类别'],
projectName:['Project name','প্রকল্পের নাম','项目名称'],location:['Location','অবস্থান','位置'],company:['Company name','কোম্পানির নাম','公司名称'],targetDate:['Target completion','লক্ষ্য সমাপ্তির তারিখ','计划竣工日期'],unitsPerLevel:['Units per level','প্রতি তলায় ইউনিট','每层单元数'],firstUnit:['First unit number','প্রথম ইউনিট নম্বর','起始单元号'],numberOfLevels:['Number of levels','তলার সংখ্যা','楼层数'],reportsSub:['Project records, ready for your next site meeting.','সাইট মিটিংয়ের জন্য প্রকল্পের হিসাব।','为下一次现场会议准备项目记录。'],download:['Download CSV','CSV ডাউনলোড','下载 CSV'],referencesSub:['Original site boards and block reference.','মূল সাইট বোর্ড ও ব্লকের নথি।','原始现场图板与楼栋参考。'],source:['Original reference','মূল নথি','原始图纸'],records:['records','তথ্য','条记录'],view:['View','দেখুন','查看'],lightMode:['Light appearance','উজ্জ্বল থিম','浅色外观'],darkMode:['Dark appearance','ডার্ক থিম','深色外观'],loading:['Loading workspace…','কর্মক্ষেত্র লোড হচ্ছে…','正在加载工作区…'],retry:['Try again','আবার চেষ্টা করুন','重试'],back:['Back','ফিরে যান','返回'],notifications:['Site alerts','সাইট সতর্কতা','现场提醒'],unitsReady:['Units ready for testing','টেস্টের জন্য প্রস্তুত ইউনিট','待测试单元'],inspect:['Inspect','পরিদর্শন','验收'],all:['All','সব','全部'],noHistory:['No updates recorded yet','এখনও কোনো আপডেট নেই','暂无更新记录'],projectSub:['Your projects, from slab to handover.','স্ল্যাব থেকে হস্তান্তর—সব প্রকল্প।','从楼板施工到交付的全部项目。'],goProject:['Open project','প্রকল্প খুলুন','打开项目'],scope:['ELECTRICAL WORKS','ইলেকট্রিক্যাল কাজ','电气工程'],scopeSub:['HDB residential development','HDB আবাসিক প্রকল্প','HDB 住宅开发'],blockOverview:['All blocks at a glance','সব ব্লক এক নজরে','楼栋概览'],noUnits:['No units in this selection','এই নির্বাচনে কোনো ইউনিট নেই','当前筛选下暂无单元'],recorded:['Recorded','সংরক্ষিত','已记录'],current:['Current','বর্তমান','当前'],power:['Power','পাওয়ার','电源'],light:['Light','লাইট','照明'],socket:['Socket','সকেট','插座'],switch:['Switch','সুইচ','开关'],data:['Data','ডাটা','数据'],tv:['TV','টিভি','电视'],unassigned:['Unassigned','নির্ধারিত নয়','未分配'],new:['New','নতুন','新建'],dueToday:['Due today','আজ নির্ধারিত','今日到期'],target:['TARGET','লক্ষ্য','目标'],
home:['Home'],users:['Users'],usersSub:['Team logins and access.'],addUser:['Add user'],
loginSub:['Sign in to your site workspace.'],identifier:['Email or phone'],identifierHint:['you@company.com or phone number'],password:['Password'],signIn:['Sign in'],signOut:['Sign out'],
email:['Email'],role:['Role'],admin:['Admin'],manager:['Manager'],engineer:['Engineer'],supervisor:['Supervisor'],worker:['Worker'],viewer:['Viewer'],
inactive:['Inactive'],activate:['Activate'],deactivate:['Deactivate'],
deactivateConfirm:['Deactivate this user? They will not be able to sign in.'],activateConfirm:['Activate this user?'],
resetPassword:['Reset password'],resetPasswordConfirm:['Reset this password? A new temporary password will be generated.'],
tempPassword:['Temporary password'],tempPasswordTitle:['Temporary password'],tempPasswordHint:['Share this one-time password with'],
copy:['Copy'],copied:['Copied'],done:['Done'],
changePassword:['Change password'],currentPassword:['Current password'],newPassword:['New password'],confirmPassword:['Confirm new password'],
passwordMismatch:['New passwords do not match.'],passwordMin:['Password must be at least 8 characters.'],passwordChanged:['Password changed.'],
mustChangePassword:['Set a new password'],mustChangePasswordSub:['Your account has a temporary password. Set a new one to continue.'],
emailOrPhoneRequired:['Email or phone is required.'],linkedWorker:['Linked worker'],
hello:['Hello'],today:['Today'],myAttendance:['My attendance'],markAttendance:['Mark attendance'],attendanceMarked:['Attendance recorded.'],siteToday:['Site today']
};
const Context=createContext(null);
export function LanguageProvider({children}) {const [lang,setLangState]=useState(()=>localStorage.getItem('voltcraft-language')||'en'); const setLang=l=>{setLangState(l);localStorage.setItem('voltcraft-language',l);document.documentElement.lang=l;};const index={en:0,bn:1,zh:2}[lang]??0;return <Context.Provider value={{lang,setLang,t:key=>words[key]?.[index]||words[key]?.[0]||key}}>{children}</Context.Provider>;}
export const useLanguage=()=>useContext(Context);